name: Checks

on: pull_request

jobs:
  composer-normalize:
    name: Composer Normalize
    runs-on: Ubuntu-20.04

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          tools: composer-normalize

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Normalize
        run: |
          ok=0
          echo ::group::Root
          composer-normalize --dry-run
          echo ::endgroup::
          for COMPONENT in $(find src -maxdepth 4 -type f -name composer.json | sort)
          do
            echo ::group::$COMPONENT
            localExit=0
            composer-normalize $COMPONENT --dry-run || localExit=1
            ok=$(( $localExit || $ok ))
            echo ::endgroup::
            if [ $localExit -ne 0 ]; then
              echo "::error::$COMPONENT failed"
            fi
          done

          exit $ok
